server:
  host: "0.0.0.0"
  port: ":8080"
  shutdownTimeout: "30s"

database:
  host: "localhost"
  port: "5432"
  user: "your_username"
  password: "your_password"
  dbname: "your_database_name"
  sslmode: "disable"

jwt:
  secret: "your_jwt_secret_key"
  tokenExpiry: "24h"
  refreshTokenExpiry: "168h"
  refreshSecret: "your_refresh_secret_key"
